spring:
  activemq:
    broker-url: tcp://localhost:61616

---
spring:
  profiles: producer
server:
  port: 9011

---
spring:
  profiles: consumer1
server:
  port: 9021

---
spring:
  profiles: consumer2
server:
  port: 9022