spring:
  rabbitmq:
    host: 192.168.1.117
    port: 5672
    username: guest
    password: guest

---
spring:
  profiles: producer
server:
  port: 9011

---
spring:
  profiles: consumer1
server:
  port: 9021

---
spring:
  profiles: consumer2
server:
  port: 9022