spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

---
spring:
  profiles: producer
server:
  port: 9011

---
spring:
  profiles: consumer1
server:
  port: 9021

---
spring:
  profiles: consumer2
server:
  port: 9022