server:
  port: 9001

spring:
  application:
    name: server-a
  cloud:
    inetutils:
      preferred-networks:
        - localhost
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-interval: 15s
        # deregister: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        # instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
        # instance-id: server-a
        # instance-id: server-a-${server.port}
        # service-name: server-a