spring:
  application:
    name: server-b
  cloud:
    inetutils:
      preferred-networks:
        - localhost
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-interval: 15s
        # instance-id: server-b
        # instance-id: server-b-${server.port}
        # service-name: server-b

---
spring:
  profiles: p02
server:
  port: 9002

---
spring:
  profiles: p03
server:
  port: 9003