server:
  port: 6853

my:
  config:
    test: seata-info-333
    user:
      name: s2-xf
      age: 22
spring:
  application:
    name: seata-info
  datasource:
    url: jdbc:mysql://localhost:3306/seata_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: abc
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: my-test
        group: group1
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

seata: # 阿里分布式事务配置
  service:
    vgroup-mapping:
      # 这里的组名 my_test_tx_group 就是上面已经配置过的
      # seata-server 对应的就是 register.conf 里的 application 选项的内容
      my_test_tx_group: seata-server
    grouplist:
      # 这里对应的就是上面的 seata-server
      seata-server: localhost:8091
    enable-degrade: false
    disable-global-transaction: false
  client:
    undo:
      log-table: undo_log_info