spring:
  profiles:
    active: s0xx

app:
  sign: sign-def


---

server:
  port: 9901

spring:
  config:
    activate:
      on-profile: s01

app:
  sign: sign-01111


---

server:
  port: 9902

spring:
  config:
    activate:
      on-profile: s02

app:
  sign: sign-02222
