spring:
  profiles:
    active: s0xx

app:
  sign: sign-def


---

server:
  port: 9901

spring:
  config:
    activate:
      on-profile: s01

app:
  sign: sign-01111

logging:
  level:
    org:
      apache:
        tomcat: info
        catalina: info
        coyote: debug   # host 解析出错好打印日志

---

server:
  port: 9902

spring:
  config:
    activate:
      on-profile: s02

app:
  sign: sign-02222

---

server:
  port: 9903

spring:
  config:
    activate:
      on-profile: s03

app:
  sign: sign-03333

---

server:
  port: 9904

spring:
  config:
    activate:
      on-profile: s04

app:
  sign: sign-04444
