spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

---
spring:
  profiles: producer
server:
  port: 9011

---
spring:
  profiles: consumer1
server:
  port: 9021

---
spring:
  profiles: consumer2
server:
  port: 9022