server:
  port: 9001

test:
  name: zxf

spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev

test:
  name: dev-0000

---
spring:
  config:
    activate:
      on-profile: prod

test:
  name: prod-2222
