### Java-基础测试
GET http://localhost:9901/test/base?test1=v1&key2=v2
Content-Type: application/json
X-UID: 8866
X-UserName: %E5%8F%9188

{"key1": "v1-009", "k2": 88}


### Nginx-加请求头-给上游
GET http://127.0.0.1:9801/test/header/nginx-add-req
Content-Type: application/json
X-UID: 8899

{"key1": "v1-009", "k2": 88}


### Nginx-加响应头-给下游
GET http://127.0.0.1:9802/test/header/nginx-add-res
Content-Type: application/json
X-UID: 9966

{"key1": "v1-009", "k2": 88}


### Nginx-保持连接
#GET http://127.0.0.1:9901/test/nginx/keepalive # 请求原始服务
GET http://127.0.0.1:9811/test/nginx/keepalive
Content-Type: application/json
X-UID: 9966

{"key1": "v1-009", "k2": 88}


### Nginx-上游主从
GET http://127.0.0.1:9812/test/nginx/master-slave
Content-Type: application/json
X-UID: 9968

{"key1": "v1-029", "k2": 88}