
### Nginx-加请求头-给上游
GET http://127.0.0.1:9801/test/header/nginx-add-req
Content-Type: application/json
X-UID: 8899

{"key1": "v1-009", "k2": 88}


### Nginx-加响应头-给下游
GET http://127.0.0.1:9802/test/header/nginx-add-res
Content-Type: application/json
X-UID: 9962

{"key1": "v1-009", "k2": 88}


### Nginx-保持连接
#GET http://127.0.0.1:9901/test/nginx/keepalive # 请求原始服务
GET http://127.0.0.1:9811/test/nginx/keepalive
Content-Type: application/json
X-UID: 9966

{"key1": "v1-009", "k2": 88}


### Nginx-上游主从
GET http://127.0.0.1:9812/test/nginx/master-slave
Content-Type: application/json
X-UID: 9968

{"key1": "v1-029", "k2": 88}


### Nginx-负载均衡-最少连接
GET http://127.0.0.1:9821/test/nginx/lb-least-conn
Content-Type: application/json
X-UID: 9978

{"key1": "v1-039", "k2": 188}


### Nginx-负载均衡-轮询
GET http://127.0.0.1:9822/test/nginx/lb-round-robin
Content-Type: application/json
X-UID: 9982

{"key1": "v1-055", "k2": 166}


### Nginx-负载均衡-随机
GET http://127.0.0.1:9823/test/nginx/lb-random
Content-Type: application/json
X-UID: 9985

{"key1": "v1-056", "k2": 168}


### Nginx-负载均衡-权重
GET http://127.0.0.1:9824/test/nginx/lb-weight
Content-Type: application/json
X-UID: 9986

{"key1": "v1-058", "k2": 18}


### Nginx-负载均衡-IP哈希
GET http://127.0.0.1:9825/test/nginx/lb-ip-hash
Content-Type: application/json
X-UID: 9988

{"key1": "v1-059", "k2": 26}


### Nginx-负载均衡-通用哈希
GET http://127.0.0.1:9826/test/nginx/lb-generic-hash/666
Content-Type: application/json
X-UID: 9989

{"key1": "v1-169", "k2": 56}


### Nginx-限流-请求数
GET http://127.0.0.1:9831/test/nginx/limit
Content-Type: application/json
X-UID: 9966

{"key1": "v1-269", "k2": 66}


### Nginx-限流-连接数
GET http://127.0.0.1:9832/test/nginx/limit
Content-Type: application/json
X-UID: 9968

{"key1": "v1-269", "k2": 66}


### Nginx-限流-限速
GET http://127.0.0.1:9833/test/nginx/limit2
Content-Type: application/json
X-UID: 9968

{"key1": "v1-269", "k2": 66}